### ISSUE TITLE
Unable to import level data

### ISSUE THREAD

**Issue by Nosen92** [toruzz/SuperMarioLandDX#1]
Trying to import the level data into a fresh ROM gives the error:
"Unable to import file: Type mismatch, 13"

Land forger 1.4.6
Windows 7

**Comment by toruzz** [comment]
I just pushed a fix, could you try again, @Nosen92?

It was an issue with git's autoCRLF, apparently.

**Comment by toruzz** [comment]
It seems to work fine now, please open another issue if you face any other problems.
