### ISSUE TITLE
Inactive SRAM access

### ISSUE THREAD

**Issue by ghost** [toruzz/SuperMarioLandDX#5]
There seems to be an instance in which the game accesses SRAM without activation. This appears to be an accidental omission of code because the same code segment in Super Mario Land 2 DX does this just fine.

**Comment by toruzz** [comment]
Could you elaborate on how you identified this problem? Is there something specific you are experiencing?

As you can see here, I simply leave SRAM enabled all the time when the game starts:
https://github.com/toruzz/SuperMarioLandDX/blob/f2f884873a5bbbe2d20f8d47e6d9ef80d2cf3355/main.asm#L252-L257

I know it's good practice to enable it for a specific data access/write and then disable it, but I use this quite heavily. If an actual issue (i.e. on real hardware) comes up, I'll consider refactoring the code to accommodate for this.

**Comment by ghost** [comment]
In the BGB emulator, options -> exceptions -> MBC -> break on access. This will result in the emulator halting to its debugger with the message "accessing inactive SRAM". Admittedly, I was debugging the rom due to it bugging out and not utilizing its save system properly on another emulator. 

SMLDX stopped at error:
![SMLDX SRAM Error](https://user-images.githubusercontent.com/38510213/167265387-2eefc6cf-cccb-413f-8579-e122771a1c7c.png)

SM2LDX same code, without the issue:
![SMLDX2 SRAM](https://user-images.githubusercontent.com/38510213/167265409-74d8a99e-5cab-4b27-9cc5-28af1cc46a1f.png)

**Comment by toruzz** [comment]
I followed your steps and noticed that the exact same thing happens with the original ROM. It doesn't seem to be a problem with this hack (or a problem at all).

I'll leave this issue open for a couple of days in case there is anything else that can be added.

**Comment by ghost** [comment]
Ok. Didn't realize that issue was part of the original rom.
